# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_DB:  user-crud
      POSTGRES_USER:  users-crud
      POSTGRES_PASSWORD: users-crud
    ports:
      - 5432:5432
