service: user-crud

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  createUser:
    handler: src/handlers/users.handler.create
    events:
      - http:
          method: post
          path: /users

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dynamodb-local

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1